language: generic
sudo: true
cache: apt
addons:
  apt:
    sources:
      - sourceline: ppa:hvr/z3
    packages:
      - z3

install:
  - curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
  - source ~/.elan/env

script:
  - leanpkg test
